hosts_file:
  - { name: gluster1, ip: 192.168.29.2 }
  - { name: gluster2, ip: 192.168.29.3 }
  - { name: gluster3, ip: 192.168.29.4 }
  - { name: glusterd, ip: 192.168.29.5 }

# this is actually gluster data nodes plus ctdb
# Because 
ctdb_nodes:
  - { name: gluster1, ip: 192.168.29.2 }
  - { name: gluster2, ip: 192.168.29.3 }

ctdb_public_addresses:
  - { network: 10.0.100.110/24, interface: ens224 }
  - { network: 10.0.100.111/24, interface: ens224 }

gluster_nodes:
  - { name: gluster1, ip: 192.168.29.2 }
  - { name: gluster2, ip: 192.168.29.3 }
  - { name: gluster3, ip: 192.168.29.4 }